export const info = {
    name: 'libretranslate',
    icon: 'logo/libretranslate.svg',
    display: 'LibreTranslate',
};

// LibreTranslate uses ISO 639-1 codes (plus `zt` for Traditional Chinese).
export enum Language {
    auto = 'auto',
    zh_cn = 'zh',
    zh_tw = 'zt',
    ja = 'ja',
    en = 'en',
    ko = 'ko',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt',
    pt_br = 'pt',
    vi = 'vi',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ar',
    hi = 'hi',
    nb_no = 'nb',
    fa = 'fa',
    sv = 'sv',
    pl = 'pl',
    nl = 'nl',
    uk = 'uk',
    he = 'he',
}
